# Generated by Django 5.2.4 on 2026-03-17 19:42

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


POSITION_MAP = {
    "Point Guard": "PG",
    "Shooting Guard": "SG",
    "Small Forward": "SF",
    "Power Forward": "PF",
    "Center": "C",
    "Guard": "G",
    "Forward": "F",
}


def normalize_positions(apps, schema_editor):
    PlayerBio = apps.get_model("nba_stats", "PlayerBio")
    to_update = []
    for bio in PlayerBio.objects.exclude(position__isnull=True):
        pos = bio.position or ""
        if len(pos) <= 2:
            continue
        bio.position = POSITION_MAP.get(pos, None)
        to_update.append(bio)
    if to_update:
        PlayerBio.objects.bulk_update(to_update, ["position"])


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0007_remove_playerbio_date"),
        ("nba_teams", "0003_nbateam"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular Season"),
                            ("Post", "Post Season"),
                        ],
                        max_length=10,
                    ),
                ),
                ("gp", models.PositiveIntegerField()),
                ("gs", models.PositiveIntegerField()),
                ("min", models.PositiveIntegerField()),
                ("fgm", models.PositiveIntegerField()),
                ("fga", models.PositiveIntegerField()),
                ("fg_pct", models.FloatField()),
                ("fg3m", models.PositiveIntegerField()),
                ("fg3a", models.PositiveIntegerField()),
                ("fg3_pct", models.FloatField()),
                ("ftm", models.PositiveIntegerField()),
                ("fta", models.PositiveIntegerField()),
                ("ft_pct", models.FloatField()),
                ("oreb", models.PositiveIntegerField()),
                ("dreb", models.PositiveIntegerField()),
                ("reb", models.PositiveIntegerField()),
                ("ast", models.PositiveIntegerField()),
                ("stl", models.PositiveIntegerField()),
                ("blk", models.PositiveIntegerField()),
                ("tov", models.PositiveIntegerField()),
                ("pf", models.PositiveIntegerField()),
                ("pts", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=500)),
                (
                    "first_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Substr(
                            "full_name",
                            1,
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.text.StrIndex(
                                    "full_name", models.Value(" ")
                                ),
                                "-",
                                models.Value(1),
                            ),
                        ),
                        output_field=models.CharField(max_length=100),
                    ),
                ),
                (
                    "last_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Substr(
                            "full_name",
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.text.StrIndex(
                                    "full_name", models.Value(" ")
                                ),
                                "+",
                                models.Value(1),
                            ),
                            django.db.models.functions.text.Length("full_name"),
                        ),
                        output_field=models.CharField(max_length=100),
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        default="https://static.vecteezy.com/system/resources/thumbnails/004/511/281/small_2x/default-avatar-photo-placeholder-profile-picture-vector.jpg"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="nba_teams.nbateam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PTS", models.FloatField(default=0)),
                ("REB", models.FloatField(default=0)),
                ("AST", models.FloatField(default=0)),
                ("BLK", models.FloatField(default=0)),
                ("STL", models.FloatField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="nba_stats.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonHigh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=20)),
                ("game_date", models.DateField()),
                ("stat_name", models.CharField(max_length=20)),
                ("stat_value", models.FloatField()),
                (
                    "opponent_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nba_teams.nbateam",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_highs",
                        to="nba_stats.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.CharField(max_length=9)),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular Season"),
                            ("Post", "Post Season"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rank_pts", models.IntegerField(blank=True, null=True)),
                ("rank_ast", models.IntegerField(blank=True, null=True)),
                ("rank_reb", models.IntegerField(blank=True, null=True)),
                ("rank_stl", models.IntegerField(blank=True, null=True)),
                ("rank_blk", models.IntegerField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_rankings",
                        to="nba_stats.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.CharField(max_length=9)),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular Season"),
                            ("Post", "Post Season"),
                        ],
                        max_length=10,
                    ),
                ),
                ("player_age", models.FloatField(blank=True, null=True)),
                ("games_played", models.PositiveIntegerField()),
                ("games_started", models.PositiveIntegerField()),
                ("minutes", models.PositiveIntegerField()),
                ("fgm", models.PositiveIntegerField()),
                ("fga", models.PositiveIntegerField()),
                ("fg_pct", models.FloatField()),
                ("fg3m", models.PositiveIntegerField()),
                ("fg3a", models.PositiveIntegerField()),
                ("fg3_pct", models.FloatField()),
                ("ftm", models.PositiveIntegerField()),
                ("fta", models.PositiveIntegerField()),
                ("ft_pct", models.FloatField()),
                ("oreb", models.PositiveIntegerField()),
                ("dreb", models.PositiveIntegerField()),
                ("reb", models.PositiveIntegerField()),
                ("ast", models.PositiveIntegerField()),
                ("stl", models.PositiveIntegerField()),
                ("blk", models.PositiveIntegerField()),
                ("tov", models.PositiveIntegerField()),
                ("pf", models.PositiveIntegerField()),
                ("pts", models.PositiveIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_stats",
                        to="nba_stats.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nba_teams.nbateam",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "season_id", "season_type")},
            },
        ),
        migrations.DeleteModel(
            name="PlayerHeadshot",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="AST",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="BLK",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="PTS",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="REB",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="STL",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="player_id",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="player_name",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="status",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="playerbio",
            name="team_name",
        ),
        migrations.AddField(
            model_name="playerbio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="playerbio",
            name="team",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="height",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_positions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="playerbio",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PG", "Point Guard"),
                    ("SG", "Shooting Guard"),
                    ("SF", "Small Forward"),
                    ("PF", "Power Forward"),
                    ("C", "Center"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="careerstat",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_stats",
                to="nba_stats.player",
            ),
        ),
        migrations.AddField(
            model_name="playerbio",
            name="player",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bio",
                to="nba_stats.player",
            ),
        ),
    ]
