# Generated by Django 5.2.4 on 2026-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0008_careerstat_player_playerstats_seasonhigh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerbio",
            name="years_pro",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
