# Generated by Django 5.2.4 on 2026-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0009_playerbio_years_pro"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="bdl_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="playerbio",
            name="draft_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerbio",
            name="draft_round",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
