# Generated by Django 5.2.4 on 2026-05-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0010_player_bdl_id_playerbio_draft_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerbio",
            name="team",
        ),
    ]
