# Generated by Django 5.2.4 on 2026-05-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0011_remove_playerbio_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerbio",
            name="year",
        ),
    ]
