# Generated by Django 5.2.4 on 2026-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0012_remove_playerbio_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerbio",
            name="years_pro",
        ),
        migrations.AddField(
            model_name="playerbio",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
