# Generated by Django 5.2.4 on 2026-05-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0013_remove_playerbio_years_pro_playerbio_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerbio",
            name="year",
        ),
        migrations.AddField(
            model_name="playerbio",
            name="draft_year",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="draft_num",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="draft_round",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="weight",
            field=models.CharField(blank=True, null=True),
        ),
    ]
