# Generated by Django 5.2.4 on 2026-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0014_remove_playerbio_year_playerbio_draft_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerbio",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PG", "Point Guard"),
                    ("SG", "Shooting Guard"),
                    ("G", "Guard"),
                    ("SF", "Small Forward"),
                    ("PF", "Power Forward"),
                    ("F", "Forward"),
                    ("C", "Center"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
