# Generated by Django 5.2.4 on 2026-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_teams", "0002_retiredplayers"),
    ]

    operations = [
        migrations.CreateModel(
            name="NBATeam",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=10)),
                (
                    "conference",
                    models.CharField(
                        choices=[
                            ("East", "Eastern Conference"),
                            ("West", "Western Conference"),
                        ],
                        max_length=5,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("primary_colour", models.CharField(default="#FFFFFF", max_length=7)),
                ("secondary_colour", models.CharField(default="#000000", max_length=7)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        default="https://media.licdn.com/dms/image/v2/C4E0BAQEke_OTftxqtQ/company-logo_200_200/company-logo_200_200/0/1660575300584/national_basketball_association_logo?e=1733356800&v=beta&t=LJiOxzNM9mfdgbHT2akuXDP2oYH3YUMDpypmkObMSyc",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "NBA Team",
                "verbose_name_plural": "NBA Teams",
                "ordering": ["conference", "city"],
            },
        ),
    ]
