# Generated by Django 5.2.4 on 2026-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_teams", "0003_nbateam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nbateam",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="https://media.licdn.com/dms/image/v2/C4E0BAQEke_OTftxqtQ/company-logo_200_200/company-logo_200_200/0/1660575300584/national_basketball_association_logo?e=1733356800&v=beta&t=LJiOxzNM9mfdgbHT2akuXDP2oYH3YUMDpypmkObMSychttps://www.nba.com/celtics/",
                null=True,
            ),
        ),
    ]
